// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYv9t0jMezEehoVWU9SZWGxqmWxvU4kSs',
    appId: '1:821352302186:web:21d572ebcdcf7e008bac13',
    messagingSenderId: '821352302186',
    projectId: 'ketabi-f9e9c',
    authDomain: 'ketabi-f9e9c.firebaseapp.com',
    storageBucket: 'ketabi-f9e9c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxT5hssbJJlDn57RFo5q_zkVGjktqrW4Y',
    appId: '1:821352302186:android:cbf4f52cec3049908bac13',
    messagingSenderId: '821352302186',
    projectId: 'ketabi-f9e9c',
    storageBucket: 'ketabi-f9e9c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCaQz0V-214Zl6QodF0tymyvI0_hggbz94',
    appId: '1:821352302186:ios:16a027946296ea918bac13',
    messagingSenderId: '821352302186',
    projectId: 'ketabi-f9e9c',
    storageBucket: 'ketabi-f9e9c.appspot.com',
    iosBundleId: 'com.example.bookSwapping',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCaQz0V-214Zl6QodF0tymyvI0_hggbz94',
    appId: '1:821352302186:ios:4d0c12b3ae46404c8bac13',
    messagingSenderId: '821352302186',
    projectId: 'ketabi-f9e9c',
    storageBucket: 'ketabi-f9e9c.appspot.com',
    iosBundleId: 'com.example.bookSwapping.RunnerTests',
  );
}
